# Generated by Django 3.2.3 on 2021-06-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllStars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='comentario',
            field=models.CharField(max_length=500, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Numero'),
        ),
    ]
